version: "3"

services:
  django:
    build: ./src
    container_name: shikin_django
    command: uwsgi --ini /code/shikin/django.ini
    # Djangoセットアップ時はcommandからuwsgiを起動せずに、ttyにする
    # tty: True
    volumes:
      - ./src:/code
    env_file:
      - ./django.env
    expose:
      - "8001"
    restart: always

  nginx:
    image: nginx:1.17.9-alpine
    container_name: shikin_nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/log/:/var/log/nginx/
      - ./src/static:/static
    depends_on:
      - django
    restart: always

networks:
  default:
    external:
      name: shared
